# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
latex: false

r:
  - release
  - devel

addons:
  apt:
    packages:
      - libnlopt-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov(type="all")'
